Add conversion of booleans and a test
bendrucker/postgres-array pull request #3
Opened 2016-12-09 02:40 UTC by royreiss

Hi, 
postgres-array isn't converting boolean arrays correctly.  Arrays of type BOOL[] are brought into node as strings.
Thanks!

2016-12-09 04:29 UTC, bendrucker requested changes
Can you clean up the final change by using typeof?

2016-12-09 19:33 UTC, bendrucker requested changes
see typeof comment

2016-12-09 19:33 UTC, bendrucker commented on index.js
> +    if (entry !== null && typeof(entry) !== 'boolean') entry = this.transform(entry)
typeof is an opertor, not a function (`typeof entry`)

2016-12-09 20:08 UTC, royreiss commented
Sorry about that!  All this time I've been using it with parens <facepalm>

2016-12-09 20:33 UTC, bendrucker requested changes
Check Travis, there are a few errors being thrown by standard. After that, LGTM.

2016-12-09 22:44 UTC, merged

2016-12-09 22:53 UTC, bendrucker commented
Hey, wasn't thinking when I reviewed this. This code doesn't belong here—I'm reverting. That's what the `transform` is for. Belongs in node-pg-types.

2016-12-10 02:35 UTC, royreiss commented
That makes a lot more sense :)  Thanks for submitting that!